--!strict
-- Color grade presets (cutscenes.md section 0). Applied by the client Grade controller with
-- tweened ColorCorrection / Bloom / Atmosphere / Lighting values plus screen overlays.

export type GradeDef = {
	brightness: number,
	contrast: number,
	saturation: number,
	tint: Color3,
	bloomIntensity: number,
	bloomSize: number,
	bloomThreshold: number,
	atmosphereDensity: number,
	atmosphereHaze: number,
	atmosphereColor: Color3,
	atmosphereDecay: Color3,
	atmosphereGlare: number,
	exposure: number,
	ambient: Color3?, -- Lighting.Ambient / OutdoorAmbient override (CAVE)
	grain: boolean,
	vignette: boolean,
	pillarbox: boolean, -- 4:3 frame
	glitch: boolean, -- RGB flicker + random red blocks
}

local rgb = Color3.fromRGB

local Grades: { [string]: GradeDef } = {
	DUSK = {
		brightness = 0.02,
		contrast = 0.08,
		saturation = 0.12,
		tint = rgb(255, 216, 176),
		bloomIntensity = 0.6,
		bloomSize = 28,
		bloomThreshold = 0.9,
		atmosphereDensity = 0.3,
		atmosphereHaze = 1.6,
		atmosphereColor = rgb(255, 190, 140),
		atmosphereDecay = rgb(160, 110, 140),
		atmosphereGlare = 0.6,
		exposure = 0.1,
		grain = false,
		vignette = false,
		pillarbox = false,
		glitch = false,
	},
	NIGHT = {
		brightness = -0.04,
		contrast = 0.25,
		saturation = -0.25,
		tint = rgb(170, 190, 255),
		bloomIntensity = 0.45,
		bloomSize = 24,
		bloomThreshold = 0.95,
		atmosphereDensity = 0.5,
		atmosphereHaze = 2.2,
		atmosphereColor = rgb(60, 70, 110),
		atmosphereDecay = rgb(40, 45, 80),
		atmosphereGlare = 0,
		exposure = -0.3,
		grain = false,
		vignette = false,
		pillarbox = false,
		glitch = false,
	},
	NIGHT_DEEP = {
		brightness = -0.06,
		contrast = 0.3,
		saturation = -0.7,
		tint = rgb(205, 210, 235),
		bloomIntensity = 0.7,
		bloomSize = 30,
		bloomThreshold = 0.9,
		atmosphereDensity = 0.55,
		atmosphereHaze = 2.5,
		atmosphereColor = rgb(40, 42, 55),
		atmosphereDecay = rgb(25, 25, 35),
		atmosphereGlare = 0,
		exposure = -0.35,
		grain = false,
		vignette = true,
		pillarbox = false,
		glitch = false,
	},
	FLASHBACK = {
		brightness = 0.05,
		contrast = 0.05,
		saturation = -0.85,
		tint = rgb(255, 226, 180),
		bloomIntensity = 0.8,
		bloomSize = 30,
		bloomThreshold = 0.8,
		atmosphereDensity = 0.3,
		atmosphereHaze = 1.2,
		atmosphereColor = rgb(220, 190, 150),
		atmosphereDecay = rgb(150, 120, 90),
		atmosphereGlare = 0.2,
		exposure = 0,
		grain = true,
		vignette = true,
		pillarbox = true,
		glitch = false,
	},
	GLITCH = {
		brightness = 0,
		contrast = 0.35,
		saturation = 0.2,
		tint = rgb(255, 235, 235),
		bloomIntensity = 0.8,
		bloomSize = 26,
		bloomThreshold = 0.85,
		atmosphereDensity = 0.45,
		atmosphereHaze = 2,
		atmosphereColor = rgb(80, 40, 60),
		atmosphereDecay = rgb(50, 20, 40),
		atmosphereGlare = 0,
		exposure = -0.1,
		grain = false,
		vignette = true,
		pillarbox = false,
		glitch = true,
	},
	DAWN = {
		brightness = 0.06,
		contrast = 0.05,
		saturation = 0.15,
		tint = rgb(255, 215, 225),
		bloomIntensity = 0.9,
		bloomSize = 36,
		bloomThreshold = 0.85,
		atmosphereDensity = 0.18,
		atmosphereHaze = 0.8,
		atmosphereColor = rgb(255, 200, 190),
		atmosphereDecay = rgb(255, 170, 120),
		atmosphereGlare = 0.8,
		exposure = 0.2,
		grain = false,
		vignette = false,
		pillarbox = false,
		glitch = false,
	},
	CAVE = {
		brightness = -0.06,
		contrast = 0.2,
		saturation = -0.2,
		tint = rgb(170, 220, 180),
		bloomIntensity = 0.7,
		bloomSize = 24,
		bloomThreshold = 0.9,
		atmosphereDensity = 0.45,
		atmosphereHaze = 1.5,
		atmosphereColor = rgb(30, 50, 35),
		atmosphereDecay = rgb(15, 30, 20),
		atmosphereGlare = 0,
		exposure = -0.5,
		ambient = rgb(20, 30, 22),
		grain = false,
		vignette = true,
		pillarbox = false,
		glitch = false,
	},
}

return Grades
