--!strict
-- Placeholder rig definitions (plain data, no Roblox types, so tools/anim_preview can read it).
-- Humanoid rigs share one blocky skeleton with elbows, wrists and knees (needed for kneeling,
-- reaching and sliding down a door). Units are studs; the rig stands on y = 0 and faces -Z.
-- Joint c0 / c1 are positions in Part0 / Part1 space, exactly like Motor6D.C0 / C1.
-- The legs hang from the HumanoidRootPart (the pelvis), so RootJoint bends only the upper body.
-- Animation angles: rot = {pitch, yaw, roll} in degrees (CFrame.Angles order).
--   Limbs hang down, so +pitch swings an arm/leg FORWARD; knees bend with -pitch, elbows +pitch.
--   Parts that point up (torso at RootJoint, head at Neck, the whole model at Root) tilt
--   FORWARD with -pitch (bow, look down) and back with +pitch.
--   +roll moves a part toward +X (the rig's right side): right arm out = +roll, left arm = -roll.
--   +yaw turns left (counter-clockwise seen from above).

export type PartDef = { size: { number } }
export type JointDef =
	{ name: string, part0: string, part1: string, c0: { number }, c1: { number } }
export type AccessoryDef = {
	name: string,
	part: string,
	size: { number },
	offset: { number },
	color: string,
	material: string?,
	transparency: number?,
	rot: { number }?, -- degrees, applied after the offset
	shape: string?, -- "Block" (default) | "Cylinder" | "Ball"
}
export type CustomPart = {
	name: string,
	size: { number },
	color: string,
	material: string?,
	transparency: number?,
	shape: string?,
}
export type CharacterDef = {
	kind: "humanoid" | "cube" | "custom",
	displayName: string,
	faceStyle: ("villager" | "screen")?,
	colors: { [string]: string }, -- part name -> hex color ("*" = default)
	accessories: { AccessoryDef }?,
	cubeSize: number?,
	cubeStretch: { number }?, -- cube kind: size multipliers (Negatino is 1.5x taller)
	material: string?,
	scale: number?, -- whole rig scale (Tung Tung is taller)
	face: string?, -- default expression
	glow: { color: string, range: number, brightness: number }?,
	multiFace: boolean?, -- Giallino Totale: a face on every side
	headMaterial: string?,
	-- custom kind (props with joints): parts + joints, the first part is the anchored root
	parts: { CustomPart }?,
	joints: { JointDef }?,
	rootHeight: number?,
	noTag: boolean?,
}

local RigSpecs = {}

-- typed wrappers so every entry is checked on its own (mixed optional fields)
local function acc(a: AccessoryDef): AccessoryDef
	return a
end

local function part(p: CustomPart): CustomPart
	return p
end

RigSpecs.skeleton = {
	rootHeight = 3.2, -- HumanoidRootPart center above the ground
	parts = {
		HumanoidRootPart = { size = { 2, 2, 1 } },
		Torso = { size = { 2, 2, 1 } },
		Head = { size = { 1.3, 1.3, 1.3 } },
		RightUpperArm = { size = { 0.9, 1.1, 0.9 } },
		RightLowerArm = { size = { 0.85, 1.0, 0.85 } },
		RightHand = { size = { 0.8, 0.4, 0.8 } },
		LeftUpperArm = { size = { 0.9, 1.1, 0.9 } },
		LeftLowerArm = { size = { 0.85, 1.0, 0.85 } },
		LeftHand = { size = { 0.8, 0.4, 0.8 } },
		RightThigh = { size = { 0.92, 1.1, 0.92 } },
		RightShin = { size = { 0.9, 1.1, 0.9 } },
		LeftThigh = { size = { 0.92, 1.1, 0.92 } },
		LeftShin = { size = { 0.9, 1.1, 0.9 } },
	} :: { [string]: PartDef },
	joints = {
		{
			name = "RootJoint",
			part0 = "HumanoidRootPart",
			part1 = "Torso",
			c0 = { 0, -1, 0 },
			c1 = { 0, -1, 0 },
		},
		{ name = "Neck", part0 = "Torso", part1 = "Head", c0 = { 0, 1, 0 }, c1 = { 0, -0.65, 0 } },
		{
			name = "RightShoulder",
			part0 = "Torso",
			part1 = "RightUpperArm",
			c0 = { 1.47, 0.75, 0 },
			c1 = { 0, 0.3, 0 },
		},
		{
			name = "RightElbow",
			part0 = "RightUpperArm",
			part1 = "RightLowerArm",
			c0 = { 0, -0.55, 0 },
			c1 = { 0, 0.5, 0 },
		},
		{
			name = "RightWrist",
			part0 = "RightLowerArm",
			part1 = "RightHand",
			c0 = { 0, -0.5, 0 },
			c1 = { 0, 0.2, 0 },
		},
		{
			name = "LeftShoulder",
			part0 = "Torso",
			part1 = "LeftUpperArm",
			c0 = { -1.47, 0.75, 0 },
			c1 = { 0, 0.3, 0 },
		},
		{
			name = "LeftElbow",
			part0 = "LeftUpperArm",
			part1 = "LeftLowerArm",
			c0 = { 0, -0.55, 0 },
			c1 = { 0, 0.5, 0 },
		},
		{
			name = "LeftWrist",
			part0 = "LeftLowerArm",
			part1 = "LeftHand",
			c0 = { 0, -0.5, 0 },
			c1 = { 0, 0.2, 0 },
		},
		{
			name = "RightHip",
			part0 = "HumanoidRootPart",
			part1 = "RightThigh",
			c0 = { 0.5, -1, 0 },
			c1 = { 0, 0.55, 0 },
		},
		{
			name = "RightKnee",
			part0 = "RightThigh",
			part1 = "RightShin",
			c0 = { 0, -0.55, 0 },
			c1 = { 0, 0.55, 0 },
		},
		{
			name = "LeftHip",
			part0 = "HumanoidRootPart",
			part1 = "LeftThigh",
			c0 = { -0.5, -1, 0 },
			c1 = { 0, 0.55, 0 },
		},
		{
			name = "LeftKnee",
			part0 = "LeftThigh",
			part1 = "LeftShin",
			c0 = { 0, -0.55, 0 },
			c1 = { 0, 0.55, 0 },
		},
	} :: { JointDef },
}

local characters: { [string]: CharacterDef } = {
	Ballerina = {
		kind = "humanoid",
		displayName = "Ballerina Cappuccina",
		faceStyle = "villager",
		colors = {
			["*"] = "#F8D5E0", -- tights
			Torso = "#F2A7C3", -- leotard
			Head = "#FAF6EE", -- the cappuccino cup
			RightUpperArm = "#F3D2B5",
			RightLowerArm = "#F3D2B5",
			RightHand = "#F3D2B5",
			LeftUpperArm = "#F3D2B5",
			LeftLowerArm = "#F3D2B5",
			LeftHand = "#F3D2B5",
		},
		accessories = {
			acc({
				name = "CupFoam",
				part = "Head",
				size = { 1.4, 0.26, 1.4 },
				offset = { 0, 0.78, 0 },
				color = "#E9D3AF",
			}),
			acc({
				name = "CupCoffee",
				part = "Head",
				size = { 1.1, 0.06, 1.1 },
				offset = { 0, 0.94, 0 },
				color = "#7A4A2A",
			}),
			acc({
				name = "CupHandle",
				part = "Head",
				size = { 0.32, 0.75, 0.26 },
				offset = { 0.8, 0, 0 },
				color = "#FAF6EE",
			}),
			acc({
				name = "Tutu",
				part = "HumanoidRootPart", -- stays at the hips when the torso bends
				size = { 2.9, 0.36, 2.0 },
				offset = { 0, -0.86, 0 },
				color = "#FFB6D5",
				material = "Fabric",
			}),
			acc({
				name = "PointeShoe",
				part = "LeftShin",
				size = { 0.96, 0.36, 1.06 },
				offset = { 0, -0.4, -0.06 },
				color = "#F7C6D9",
				material = "Fabric",
			}),
			acc({
				name = "PointeShoeR",
				part = "RightShin",
				size = { 0.96, 0.36, 1.06 },
				offset = { 0, -0.4, -0.06 },
				color = "#F7C6D9",
				material = "Fabric",
			}),
		},
	},
	Giallino = {
		kind = "cube",
		displayName = "Giallino",
		faceStyle = "screen",
		colors = { ["*"] = "#FFD83A" },
		cubeSize = 4, -- one block
		material = "Neon",
	},
	Dummy = {
		kind = "humanoid",
		displayName = "Test Dummy",
		faceStyle = "villager",
		colors = { ["*"] = "#A0A4B0", Torso = "#6C7A96", Head = "#D9C7A8" },
	},

	------------------------------------------------------------------ villagers
	TungTung = {
		kind = "humanoid",
		displayName = "Tung Tung Tung Sahur",
		faceStyle = "villager",
		scale = 1.15,
		colors = { ["*"] = "#B07A48", Head = "#C08A55" },
		accessories = {
			acc({
				name = "Bat",
				part = "RightHand",
				-- held upright in front of the forearm, so it never sinks into the ground
				size = { 0.5, 3.2, 0.5 },
				offset = { 0, 1.2, -0.45 },
				color = "#7A4E28",
				material = "Wood",
			}),
			acc({
				name = "Ring1",
				part = "Torso",
				size = { 2.05, 0.14, 1.05 },
				offset = { 0, 0.35, 0 },
				color = "#8A5A30",
			}),
			acc({
				name = "Ring2",
				part = "Torso",
				size = { 2.05, 0.14, 1.05 },
				offset = { 0, -0.45, 0 },
				color = "#8A5A30",
			}),
			-- the board of names on his belt; BoardInHand / Knife are shown by cutscene cues
			acc({
				name = "NameBoard",
				part = "Torso",
				size = { 0.9, 0.6, 0.12 },
				offset = { -0.5, -0.7, -0.57 },
				color = "#8A5A30",
				material = "WoodPlanks",
			}),
			acc({
				name = "BoardInHand",
				part = "LeftHand",
				size = { 1.2, 0.8, 0.12 },
				offset = { 0, -0.5, -0.4 },
				color = "#8A5A30",
				material = "WoodPlanks",
				transparency = 1,
			}),
			acc({
				name = "Knife",
				part = "RightHand",
				size = { 0.12, 0.7, 0.2 },
				offset = { 0, -0.55, -0.3 },
				color = "#C8C8D0",
				material = "Metal",
				transparency = 1,
			}),
		},
	},
	Lirili = {
		kind = "humanoid",
		displayName = "Lirili Larila",
		faceStyle = "villager",
		colors = { ["*"] = "#5E9E4E", Head = "#6DAE5C" },
		accessories = {
			acc({
				name = "Trunk",
				part = "Head",
				size = { 0.36, 1.2, 0.36 },
				offset = { 0, -0.55, -0.8 },
				rot = { -20, 0, 0 },
				color = "#5E9E4E",
			}),
			acc({
				name = "EarL",
				part = "Head",
				size = { 0.15, 0.9, 0.8 },
				offset = { -0.74, 0.1, 0 },
				color = "#4E8E3E",
			}),
			acc({
				name = "EarR",
				part = "Head",
				size = { 0.15, 0.9, 0.8 },
				offset = { 0.74, 0.1, 0 },
				color = "#4E8E3E",
			}),
			acc({
				name = "Spine1",
				part = "Torso",
				size = { 0.1, 0.3, 0.1 },
				offset = { -0.6, 0.5, -0.55 },
				color = "#E8F0C0",
			}),
			acc({
				name = "Spine2",
				part = "Torso",
				size = { 0.1, 0.3, 0.1 },
				offset = { 0.5, -0.2, -0.55 },
				color = "#E8F0C0",
			}),
			acc({
				name = "Spine3",
				part = "Torso",
				size = { 0.1, 0.3, 0.1 },
				offset = { 0, 0.2, 0.55 },
				color = "#E8F0C0",
			}),
			acc({
				name = "Clock",
				part = "LeftHand",
				size = { 0.7, 0.7, 0.15 },
				offset = { 0, -0.35, -0.35 },
				color = "#E0C060",
				material = "Metal",
			}),
			acc({
				name = "Tear",
				part = "Head",
				size = { 0.12, 0.2, 0.05 },
				offset = { 0.3, -0.05, -0.67 },
				color = "#9AD8FF",
				material = "Glass",
				transparency = 1,
			}),
		},
	},
	Tralalero = {
		kind = "humanoid",
		displayName = "Tralalero Tralala",
		faceStyle = "villager",
		colors = { ["*"] = "#7A8CA0" },
		accessories = {
			acc({
				name = "Fin",
				part = "Head",
				size = { 0.16, 0.9, 0.9 },
				offset = { 0, 1.05, 0.1 },
				color = "#6A7C90",
			}),
			acc({
				name = "Belly",
				part = "Torso",
				size = { 1.4, 1.4, 0.06 },
				offset = { 0, -0.2, -0.53 },
				color = "#E8EEF4",
			}),
			acc({
				name = "Teeth",
				part = "Head",
				size = { 0.9, 0.12, 0.05 },
				offset = { 0, -0.42, -0.67 },
				color = "#FFFFFF",
			}),
			acc({
				name = "ShoeL",
				part = "LeftShin",
				size = { 0.98, 0.36, 1.15 },
				offset = { 0, -0.4, -0.08 },
				color = "#2E6BE0",
			}),
			acc({
				name = "ShoeR",
				part = "RightShin",
				size = { 0.98, 0.36, 1.15 },
				offset = { 0, -0.4, -0.08 },
				color = "#2E6BE0",
			}),
			acc({
				name = "SoleL",
				part = "LeftShin",
				size = { 1.0, 0.1, 1.18 },
				offset = { 0, -0.6, -0.08 },
				color = "#FFFFFF",
			}),
			acc({
				name = "SoleR",
				part = "RightShin",
				size = { 1.0, 0.1, 1.18 },
				offset = { 0, -0.6, -0.08 },
				color = "#FFFFFF",
			}),
		},
	},
	Chimpanzini = {
		kind = "humanoid",
		displayName = "Chimpanzini Bananini",
		faceStyle = "villager",
		colors = {
			["*"] = "#F2D24B",
			Head = "#6B4A2B",
			RightUpperArm = "#6B4A2B",
			RightLowerArm = "#6B4A2B",
			RightHand = "#6B4A2B",
			LeftUpperArm = "#6B4A2B",
			LeftLowerArm = "#6B4A2B",
			LeftHand = "#6B4A2B",
		},
		accessories = {
			acc({
				name = "PeelL",
				part = "Torso",
				size = { 0.3, 1.3, 0.8 },
				offset = { -1.15, -0.6, 0 },
				rot = { 0, 0, -25 },
				color = "#E8C43A",
			}),
			acc({
				name = "PeelR",
				part = "Torso",
				size = { 0.3, 1.3, 0.8 },
				offset = { 1.15, -0.6, 0 },
				rot = { 0, 0, 25 },
				color = "#E8C43A",
			}),
			acc({
				name = "Muzzle",
				part = "Head",
				size = { 0.8, 0.5, 0.12 },
				offset = { 0, -0.32, -0.67 },
				color = "#C9A27A",
			}),
			acc({
				name = "Stem",
				part = "Head",
				size = { 0.3, 0.45, 0.3 },
				offset = { 0, 0.88, 0 },
				color = "#5A4020",
			}),
			acc({
				name = "Apple",
				part = "RightHand",
				size = { 0.5, 0.5, 0.5 },
				offset = { 0, -0.4, -0.2 },
				color = "#C82828",
				shape = "Ball",
			}),
		},
	},
	Patapim = {
		kind = "humanoid",
		displayName = "Brr Brr Patapim",
		faceStyle = "villager",
		scale = 1.2,
		colors = { ["*"] = "#6B4A2B", Head = "#7A5632" },
		accessories = {
			acc({
				name = "Leaves",
				part = "Head",
				size = { 1.9, 1.0, 1.9 },
				offset = { 0, 1.1, 0 },
				color = "#3E7A2E",
				material = "Grass",
			}),
			acc({
				name = "BranchL",
				part = "Torso",
				size = { 0.3, 1.3, 0.3 },
				offset = { -1.25, 1.2, 0 },
				rot = { 0, 0, 35 },
				color = "#5A3C22",
				material = "Wood",
			}),
			acc({
				name = "BranchR",
				part = "Torso",
				size = { 0.3, 1.3, 0.3 },
				offset = { 1.25, 1.2, 0 },
				rot = { 0, 0, -35 },
				color = "#5A3C22",
				material = "Wood",
			}),
			acc({
				name = "Moss",
				part = "Torso",
				size = { 1.2, 0.5, 0.06 },
				offset = { 0.3, 0.4, -0.53 },
				color = "#4E8A3E",
				material = "Grass",
			}),
			acc({
				name = "RootL",
				part = "LeftShin",
				size = { 1.3, 0.28, 1.5 },
				offset = { 0, -0.55, 0 },
				color = "#4A3220",
			}),
			acc({
				name = "RootR",
				part = "RightShin",
				size = { 1.3, 0.28, 1.5 },
				offset = { 0, -0.55, 0 },
				color = "#4A3220",
			}),
		},
	},
	Bombardiro = {
		kind = "humanoid",
		displayName = "Bombardiro Crocodilo",
		faceStyle = "villager",
		colors = { ["*"] = "#4E7A3A", Torso = "#5A6A4A" },
		accessories = {
			acc({
				name = "Snout",
				part = "Head",
				size = { 0.9, 0.5, 1.1 },
				offset = { 0, -0.25, -1.15 },
				color = "#4E7A3A",
			}),
			acc({
				name = "Goggles",
				part = "Head",
				size = { 1.12, 0.32, 0.1 },
				offset = { 0, 0.22, -0.67 },
				color = "#3A3A3A",
			}),
			acc({
				name = "WingL",
				part = "Torso",
				size = { 3.2, 0.16, 1.0 },
				offset = { -2.7, 0.4, 0.2 },
				color = "#8A9098",
				material = "Metal",
			}),
			acc({
				name = "WingR",
				part = "Torso",
				size = { 3.2, 0.16, 1.0 },
				offset = { 2.7, 0.4, 0.2 },
				color = "#8A9098",
				material = "Metal",
			}),
			acc({
				name = "Bandage",
				part = "Torso",
				size = { 0.5, 0.5, 1.1 },
				offset = { 1.9, 0.4, 0.2 },
				color = "#F0F0E8",
				transparency = 1,
			}),
		},
	},
	Cappuccino = {
		kind = "humanoid",
		displayName = "Cappuccino Assassino",
		faceStyle = "villager",
		colors = { ["*"] = "#2A2A30", Head = "#FAF6EE" },
		accessories = {
			acc({
				name = "CupFoam",
				part = "Head",
				size = { 1.4, 0.26, 1.4 },
				offset = { 0, 0.78, 0 },
				color = "#B8865A",
			}),
			acc({
				name = "CupHandle",
				part = "Head",
				size = { 0.32, 0.75, 0.26 },
				offset = { 0.8, 0, 0 },
				color = "#FAF6EE",
			}),
			acc({
				name = "Mask",
				part = "Head",
				size = { 1.32, 0.35, 0.05 },
				offset = { 0, -0.38, -0.67 },
				color = "#2A2A30",
			}),
			acc({
				name = "Scarf",
				part = "Torso",
				size = { 2.06, 0.32, 1.06 },
				offset = { 0, 0.85, 0 },
				color = "#A42E2E",
				material = "Fabric",
			}),
			acc({
				name = "Katana",
				part = "Torso",
				size = { 0.15, 2.6, 0.25 },
				offset = { 0.5, 0, 0.6 },
				rot = { 0, 0, 30 },
				color = "#C8C8D0",
				material = "Metal",
			}),
			acc({
				name = "Shoe",
				part = "RightHand",
				size = { 0.5, 0.35, 0.9 },
				offset = { 0, -0.4, -0.3 },
				color = "#F7C6D9",
				material = "Fabric",
				transparency = 1,
			}),
		},
	},

	------------------------------------------------------------------ daytime cameos + the fruit couple
	TrippiTroppi = {
		kind = "humanoid",
		displayName = "Trippi Troppi",
		faceStyle = "villager",
		colors = { ["*"] = "#F08A50", Head = "#F0A070" },
		accessories = {
			acc({
				name = "EarL",
				part = "Head",
				size = { 0.35, 0.4, 0.2 },
				offset = { -0.45, 0.8, 0 },
				color = "#F0A070",
			}),
			acc({
				name = "EarR",
				part = "Head",
				size = { 0.35, 0.4, 0.2 },
				offset = { 0.45, 0.8, 0 },
				color = "#F0A070",
			}),
			acc({
				name = "Tail",
				part = "Torso",
				size = { 0.6, 0.4, 1.4 },
				offset = { 0, -0.8, 1.1 },
				color = "#E07040",
			}),
		},
	},
	BonecaAmbalabu = {
		kind = "humanoid",
		displayName = "Boneca Ambalabu",
		faceStyle = "villager",
		colors = { ["*"] = "#5EA04E" },
		accessories = {
			acc({
				name = "Tire",
				part = "HumanoidRootPart",
				size = { 2.9, 0.7, 2.1 },
				offset = { 0, -0.9, 0 },
				color = "#222222",
			}),
			acc({
				name = "EyeL",
				part = "Head",
				size = { 0.4, 0.35, 0.35 },
				offset = { -0.35, 0.75, -0.3 },
				color = "#7EC06E",
			}),
			acc({
				name = "EyeR",
				part = "Head",
				size = { 0.4, 0.35, 0.35 },
				offset = { 0.35, 0.75, -0.3 },
				color = "#7EC06E",
			}),
		},
	},
	UdinDinDinDun = {
		kind = "humanoid",
		displayName = "Udin Din Din Dun",
		faceStyle = "villager",
		colors = { ["*"] = "#9A70C0", Head = "#B48ED8" },
		accessories = {
			acc({
				name = "Drum",
				part = "Torso",
				size = { 1.2, 0.8, 1.2 },
				offset = { 0, -0.6, -0.9 },
				color = "#C84040",
				shape = "Cylinder",
				rot = { 0, 0, 90 },
			}),
			acc({
				name = "Hat",
				part = "Head",
				size = { 1.0, 0.5, 1.0 },
				offset = { 0, 0.9, 0 },
				color = "#6A4A90",
			}),
		},
	},
	LaVacaSaturno = {
		kind = "humanoid",
		displayName = "La Vaca Saturno Saturnita",
		faceStyle = "villager",
		colors = { ["*"] = "#F4F4F4" },
		accessories = {
			acc({
				name = "Spot1",
				part = "Torso",
				size = { 0.7, 0.6, 0.06 },
				offset = { -0.4, 0.3, -0.53 },
				color = "#202020",
			}),
			acc({
				name = "Spot2",
				part = "Torso",
				size = { 0.5, 0.5, 0.06 },
				offset = { 0.5, -0.5, 0.53 },
				color = "#202020",
			}),
			acc({
				name = "Ring",
				part = "Torso",
				size = { 3.6, 0.12, 3.6 },
				offset = { 0, 0, 0 },
				rot = { 12, 0, 8 },
				color = "#E0C070",
				shape = "Cylinder",
			}),
			acc({
				name = "HornL",
				part = "Head",
				size = { 0.2, 0.4, 0.2 },
				offset = { -0.5, 0.8, 0 },
				color = "#E8E0C0",
			}),
			acc({
				name = "HornR",
				part = "Head",
				size = { 0.2, 0.4, 0.2 },
				offset = { 0.5, 0.8, 0 },
				color = "#E8E0C0",
			}),
		},
	},
	FrigoCamelo = {
		kind = "humanoid",
		displayName = "Frigo Camelo",
		faceStyle = "villager",
		colors = { ["*"] = "#C9A06A", Torso = "#E8EEF0" },
		accessories = {
			acc({
				name = "Handle",
				part = "Torso",
				size = { 0.12, 0.9, 0.12 },
				offset = { 0.7, 0.2, -0.56 },
				color = "#A0A8B0",
				material = "Metal",
			}),
			acc({
				name = "Hump",
				part = "Torso",
				size = { 1.2, 0.8, 0.6 },
				offset = { 0, 0.9, 0.7 },
				color = "#C9A06A",
			}),
		},
	},
	GlorboFruttodrillo = {
		kind = "humanoid",
		displayName = "Glorbo Fruttodrillo",
		faceStyle = "villager",
		colors = { ["*"] = "#3E8A3A", Head = "#D84040" },
		accessories = {
			acc({
				name = "Stripe1",
				part = "Torso",
				size = { 0.2, 2.02, 1.02 },
				offset = { -0.5, 0, 0 },
				color = "#2A6A2A",
			}),
			acc({
				name = "Stripe2",
				part = "Torso",
				size = { 0.2, 2.02, 1.02 },
				offset = { 0.5, 0, 0 },
				color = "#2A6A2A",
			}),
			acc({
				name = "Snout",
				part = "Head",
				size = { 0.8, 0.4, 0.9 },
				offset = { 0, -0.3, -1.0 },
				color = "#3E8A3A",
			}),
		},
	},
	Strawberry = {
		kind = "humanoid",
		displayName = "Strawberry",
		faceStyle = "villager",
		colors = { ["*"] = "#5E9E4E", Torso = "#D83040", Head = "#E04050" },
		accessories = {
			acc({
				name = "Leaves",
				part = "Head",
				size = { 1.4, 0.3, 1.4 },
				offset = { 0, 0.8, 0 },
				color = "#4E9E3E",
				material = "Grass",
			}),
		},
	},
	Banana = {
		kind = "humanoid",
		displayName = "Banana",
		faceStyle = "villager",
		colors = { ["*"] = "#F2D24B" },
		accessories = {
			acc({
				name = "Tip",
				part = "Head",
				size = { 0.4, 0.4, 0.4 },
				offset = { 0, 0.85, 0 },
				color = "#5A4020",
			}),
		},
	},

	------------------------------------------------------------------ Giallino's forms
	Falsino = {
		kind = "cube",
		displayName = "Falsino",
		faceStyle = "screen",
		colors = { ["*"] = "#F2C83A" },
		cubeSize = 4,
		material = "Neon",
		face = "smile_crooked",
		glow = { color = "#E8E060", range = 16, brightness = 1.4 },
	},
	Negatino = {
		kind = "cube",
		displayName = "Negatino",
		faceStyle = "screen",
		colors = { ["*"] = "#1E2A6A" },
		cubeSize = 4,
		cubeStretch = { 1, 1.5, 1 },
		material = "SmoothPlastic",
		face = "neutral",
		glow = { color = "#4060FF", range = 10, brightness = 0.4 },
	},
	Crudelino = {
		kind = "cube",
		displayName = "Crudelino",
		faceStyle = "screen",
		colors = { ["*"] = "#C0281E" },
		cubeSize = 4,
		material = "Neon",
		face = "angry",
		glow = { color = "#FF3020", range = 18, brightness = 2 },
		accessories = {
			acc({
				name = "Crack1",
				part = "Body",
				size = { 3.0, 0.14, 0.06 },
				offset = { 0, 1.2, -2.02 },
				rot = { 0, 0, 25 },
				color = "#200404",
			}),
			acc({
				name = "Crack2",
				part = "Body",
				size = { 0.14, 2.6, 0.06 },
				offset = { -1.4, -0.6, -2.02 },
				rot = { 0, 0, -15 },
				color = "#200404",
			}),
			acc({
				name = "Crack3",
				part = "Body",
				size = { 0.06, 2.4, 0.14 },
				offset = { 2.02, 0.2, 0.5 },
				rot = { 20, 0, 0 },
				color = "#200404",
			}),
			acc({
				name = "Crack4",
				part = "Body",
				size = { 2.5, 0.06, 0.14 },
				offset = { 0, 2.02, 0 },
				rot = { 0, 30, 0 },
				color = "#200404",
			}),
		},
	},
	GiallinoTotale = {
		kind = "cube",
		displayName = "Giallino Totale",
		faceStyle = "screen",
		colors = { ["*"] = "#FFB030" },
		cubeSize = 4,
		material = "Neon",
		face = "happy",
		multiFace = true,
		glow = { color = "#FFB030", range = 60, brightness = 3 },
		accessories = {
			acc({
				name = "Crack1",
				part = "Body",
				size = { 3.2, 0.12, 0.06 },
				offset = { 0.3, 1.5, -2.02 },
				rot = { 0, 0, 20 },
				color = "#3A1A00",
			}),
			acc({
				name = "Crack2",
				part = "Body",
				size = { 0.06, 3.0, 0.12 },
				offset = { 2.02, -0.3, -0.8 },
				rot = { 15, 0, 0 },
				color = "#3A1A00",
			}),
			acc({
				name = "Crack3",
				part = "Body",
				size = { 0.12, 3.0, 0.06 },
				offset = { -1.2, 0, 2.02 },
				rot = { 0, 0, -20 },
				color = "#3A1A00",
			}),
			acc({
				name = "Crack4",
				part = "Body",
				size = { 0.06, 3.2, 0.12 },
				offset = { -2.02, 0.4, 0.6 },
				rot = { -10, 0, 0 },
				color = "#3A1A00",
			}),
		},
	},

	------------------------------------------------------------------ cutscene props (custom rigs)
	Door = {
		kind = "custom",
		displayName = "Door",
		colors = {},
		noTag = true,
		rootHeight = 3.5,
		parts = {
			part({ name = "Hinge", size = { 0.2, 7, 0.2 }, color = "#000000", transparency = 1 }),
			part({
				name = "Panel",
				size = { 4, 7, 0.45 },
				color = "#7A5230",
				material = "WoodPlanks",
			}),
		},
		joints = {
			{
				name = "DoorHinge",
				part0 = "Hinge",
				part1 = "Panel",
				c0 = { 0, 0, 0 },
				c1 = { -2, 0, 0 },
			},
		},
		accessories = {
			acc({
				name = "Knob",
				part = "Panel",
				size = { 0.3, 0.3, 0.6 },
				offset = { 1.5, 0, 0 },
				color = "#C0A040",
				material = "Metal",
			}),
		},
	},
	Minecart = {
		kind = "custom",
		displayName = "Minecart",
		colors = {},
		noTag = true,
		rootHeight = 1.0,
		parts = {
			part({ name = "Base", size = { 3.6, 0.4, 5.2 }, color = "#5A5A60", material = "Metal" }),
			part({
				name = "Bar",
				size = { 3.4, 0.25, 0.25 },
				color = "#9A9AA0",
				material = "Metal",
			}),
		},
		joints = {
			{
				name = "BarHinge",
				part0 = "Base",
				part1 = "Bar",
				c0 = { 0, 2.2, -2.2 },
				c1 = { 0, 0, 0 },
			},
		},
		accessories = {
			acc({
				name = "WallL",
				part = "Base",
				size = { 0.3, 1.8, 5.2 },
				offset = { -1.65, 1.1, 0 },
				color = "#6A6A70",
				material = "Metal",
			}),
			acc({
				name = "WallR",
				part = "Base",
				size = { 0.3, 1.8, 5.2 },
				offset = { 1.65, 1.1, 0 },
				color = "#6A6A70",
				material = "Metal",
			}),
			acc({
				name = "WallF",
				part = "Base",
				size = { 3.6, 1.8, 0.3 },
				offset = { 0, 1.1, -2.45 },
				color = "#6A6A70",
				material = "Metal",
			}),
			acc({
				name = "WallB",
				part = "Base",
				size = { 3.6, 1.8, 0.3 },
				offset = { 0, 1.1, 2.45 },
				color = "#6A6A70",
				material = "Metal",
			}),
			acc({
				name = "WheelFL",
				part = "Base",
				size = { 0.4, 1.0, 1.0 },
				offset = { -1.7, -0.5, -1.7 },
				color = "#2A2A2A",
				shape = "Cylinder",
			}),
			acc({
				name = "WheelFR",
				part = "Base",
				size = { 0.4, 1.0, 1.0 },
				offset = { 1.7, -0.5, -1.7 },
				color = "#2A2A2A",
				shape = "Cylinder",
			}),
			acc({
				name = "WheelBL",
				part = "Base",
				size = { 0.4, 1.0, 1.0 },
				offset = { -1.7, -0.5, 1.7 },
				color = "#2A2A2A",
				shape = "Cylinder",
			}),
			acc({
				name = "WheelBR",
				part = "Base",
				size = { 0.4, 1.0, 1.0 },
				offset = { 1.7, -0.5, 1.7 },
				color = "#2A2A2A",
				shape = "Cylinder",
			}),
		},
	},
	Gears = {
		kind = "custom",
		displayName = "Gears",
		colors = {},
		noTag = true,
		rootHeight = 0,
		parts = {
			part({ name = "Axle", size = { 0.4, 0.4, 0.4 }, color = "#3A3A3A", material = "Metal" }),
			part({
				name = "Gear1",
				size = { 0.4, 3.0, 3.0 },
				color = "#E0B040",
				material = "Metal",
				shape = "Cylinder",
			}),
			part({
				name = "Gear2",
				size = { 0.4, 2.2, 2.2 },
				color = "#E0B040",
				material = "Metal",
				shape = "Cylinder",
			}),
			part({
				name = "Gear3",
				size = { 0.4, 1.8, 1.8 },
				color = "#E0B040",
				material = "Metal",
				shape = "Cylinder",
			}),
		},
		joints = {
			{ name = "Gear1", part0 = "Axle", part1 = "Gear1", c0 = { 0, 0, 0 }, c1 = { 0, 0, 0 } },
			{
				name = "Gear2",
				part0 = "Axle",
				part1 = "Gear2",
				c0 = { 0, 2.5, 0.2 },
				c1 = { 0, 0, 0 },
			},
			{
				name = "Gear3",
				part0 = "Axle",
				part1 = "Gear3",
				c0 = { 0, -0.6, 2.4 },
				c1 = { 0, 0, 0 },
			},
		},
	},
	Sign = {
		kind = "custom",
		displayName = "Sign",
		colors = {},
		noTag = true,
		rootHeight = 0,
		parts = {
			part({ name = "Post", size = { 0.4, 4, 0.4 }, color = "#7A5230", material = "Wood" }),
			part({
				name = "Board",
				size = { 4, 2, 0.3 },
				color = "#B08A5A",
				material = "WoodPlanks",
			}),
		},
		joints = {
			{
				name = "BoardJoint",
				part0 = "Post",
				part1 = "Board",
				c0 = { 0, 1.6, 0 },
				c1 = { 0, 0, 0 },
			},
		},
	},
	Gate = {
		kind = "custom",
		displayName = "Barn gate",
		colors = {},
		noTag = true,
		rootHeight = 6,
		parts = {
			part({ name = "Hinge", size = { 0.2, 12, 0.2 }, color = "#000000", transparency = 1 }),
			part({
				name = "Panel",
				size = { 6, 12, 0.5 },
				color = "#5A1A12",
				material = "WoodPlanks",
			}),
		},
		joints = {
			{
				name = "DoorHinge",
				part0 = "Hinge",
				part1 = "Panel",
				c0 = { 0, 0, 0 },
				c1 = { -3, 0, 0 },
			},
		},
		accessories = {
			acc({
				name = "Brace",
				part = "Panel",
				size = { 6.6, 0.5, 0.6 },
				offset = { 0, 0, 0 },
				rot = { 0, 0, 55 },
				color = "#3A120C",
				material = "Wood",
			}),
		},
	},
	HandLantern = {
		kind = "custom",
		displayName = "Lantern",
		colors = {},
		noTag = true,
		rootHeight = 0,
		glow = { color = "#FFB050", range = 18, brightness = 1.8 },
		parts = {
			part({
				name = "Lamp",
				size = { 0.9, 1.1, 0.9 },
				color = "#FFE0A0",
				material = "Glass",
				transparency = 0.25,
			}),
		},
		accessories = {
			acc({
				name = "Top",
				part = "Lamp",
				size = { 1.0, 0.2, 1.0 },
				offset = { 0, 0.65, 0 },
				color = "#3A3A3A",
				material = "Metal",
			}),
			acc({
				name = "Base",
				part = "Lamp",
				size = { 1.0, 0.2, 1.0 },
				offset = { 0, -0.65, 0 },
				color = "#3A3A3A",
				material = "Metal",
			}),
			acc({
				name = "Handle",
				part = "Lamp",
				size = { 0.12, 0.6, 0.12 },
				offset = { 0, 1.0, 0 },
				color = "#3A3A3A",
				material = "Metal",
			}),
			acc({
				name = "Flame",
				part = "Lamp",
				size = { 0.3, 0.45, 0.3 },
				offset = { 0, -0.1, 0 },
				color = "#FF9A2A",
				material = "Neon",
			}),
		},
	},
	CuckooClock = {
		kind = "custom",
		displayName = "Cuckoo clock",
		colors = {},
		noTag = true,
		rootHeight = 0,
		parts = {
			part({
				name = "Case",
				size = { 2.4, 3, 1 },
				color = "#7A4E28",
				material = "WoodPlanks",
			}),
			part({ name = "Bird", size = { 0.6, 0.6, 0.9 }, color = "#F2D24B" }),
		},
		joints = {
			{
				name = "BirdJoint",
				part0 = "Case",
				part1 = "Bird",
				c0 = { 0, 0.6, -0.4 },
				c1 = { 0, 0, 0 },
			},
		},
		accessories = {
			acc({
				name = "Dial",
				part = "Case",
				size = { 0.1, 1.6, 1.6 },
				offset = { 0, -0.4, -0.52 },
				rot = { 0, 90, 0 },
				color = "#F0E6C8",
				shape = "Cylinder",
			}),
			acc({
				name = "Roof",
				part = "Case",
				size = { 2.8, 0.4, 1.3 },
				offset = { 0, 1.7, 0 },
				color = "#5A3418",
				material = "WoodPlanks",
			}),
		},
	},
	Bomb = {
		kind = "custom",
		displayName = "Bomb",
		colors = {},
		noTag = true,
		rootHeight = 0,
		parts = {
			part({
				name = "Shell",
				size = { 1.6, 1.6, 1.6 },
				color = "#222222",
				material = "Metal",
				shape = "Ball",
			}),
		},
		accessories = {
			acc({
				name = "Fuse",
				part = "Shell",
				size = { 0.2, 0.6, 0.2 },
				offset = { 0, 0.95, 0 },
				color = "#FF9A2A",
				material = "Neon",
			}),
		},
	},
	TruthGear = {
		kind = "custom",
		displayName = "Truth Gear",
		colors = {},
		noTag = true,
		rootHeight = 0,
		glow = { color = "#FFD86A", range = 10, brightness = 1.2 },
		parts = {
			part({
				name = "Gear",
				size = { 0.4, 2.2, 2.2 },
				color = "#E0B040",
				material = "Metal",
				shape = "Cylinder",
			}),
		},
		accessories = {
			acc({
				name = "Hub",
				part = "Gear",
				size = { 0.6, 0.7, 0.7 },
				offset = { 0, 0, 0 },
				color = "#FFF0A0",
				material = "Neon",
				shape = "Cylinder",
			}),
		},
	},
	LampPlate = {
		kind = "custom",
		displayName = "Plate with a little lamp",
		colors = {},
		noTag = true,
		rootHeight = 0,
		glow = { color = "#FFD83A", range = 8, brightness = 0.9 },
		parts = { part({ name = "Plate", size = { 1.6, 0.12, 1.6 }, color = "#F0F0E8" }) },
		accessories = {
			acc({
				name = "Lamp",
				part = "Plate",
				size = { 0.5, 0.5, 0.5 },
				offset = { 0, 0.32, 0 },
				color = "#FFD83A",
				material = "Neon",
			}),
		},
	},
	GlitchlingRig = {
		kind = "custom",
		displayName = "Glitchling",
		colors = {},
		noTag = true,
		rootHeight = 1.2,
		parts = { part({ name = "Body", size = { 2.4, 2.4, 2.4 }, color = "#14121A" }) },
		accessories = {
			acc({
				name = "Eye",
				part = "Body",
				size = { 0.7, 0.7, 0.1 },
				offset = { 0, 0.3, -1.25 },
				color = "#FFD83A",
				material = "Neon",
			}),
			acc({
				name = "Pixel1",
				part = "Body",
				size = { 0.5, 0.5, 0.5 },
				offset = { 1.5, 0.8, 0.3 },
				color = "#231E2D",
			}),
			acc({
				name = "Pixel2",
				part = "Body",
				size = { 0.5, 0.5, 0.5 },
				offset = { -1.4, -0.6, -0.4 },
				color = "#231E2D",
			}),
		},
	},
	WallChunk = {
		kind = "custom",
		displayName = "Wall chunk",
		colors = {},
		noTag = true,
		rootHeight = 8,
		parts = {
			part({ name = "B11", size = { 4, 4, 2 }, color = "#707070", material = "Slate" }),
			part({ name = "B12", size = { 4, 4, 2 }, color = "#6A6A6A", material = "Slate" }),
			part({ name = "B13", size = { 4, 4, 2 }, color = "#5A5A5A", material = "Slate" }),
			part({ name = "B21", size = { 4, 4, 2 }, color = "#6A6A6A", material = "Slate" }),
			part({ name = "B22", size = { 4, 4, 2 }, color = "#707070", material = "Slate" }),
			part({ name = "B23", size = { 4, 4, 2 }, color = "#666666", material = "Slate" }),
			part({ name = "B31", size = { 4, 4, 2 }, color = "#5E5E5E", material = "Slate" }),
			part({ name = "B32", size = { 4, 4, 2 }, color = "#6A6A6A", material = "Slate" }),
			part({ name = "B33", size = { 4, 4, 2 }, color = "#707070", material = "Slate" }),
		},
		joints = {
			{ name = "J12", part0 = "B11", part1 = "B12", c0 = { 4, 0, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J13", part0 = "B11", part1 = "B13", c0 = { -4, 0, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J21", part0 = "B11", part1 = "B21", c0 = { 0, 4, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J22", part0 = "B11", part1 = "B22", c0 = { 4, 4, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J23", part0 = "B11", part1 = "B23", c0 = { -4, 4, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J31", part0 = "B11", part1 = "B31", c0 = { 0, -4, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J32", part0 = "B11", part1 = "B32", c0 = { 4, -4, 0 }, c1 = { 0, 0, 0 } },
			{ name = "J33", part0 = "B11", part1 = "B33", c0 = { -4, -4, 0 }, c1 = { 0, 0, 0 } },
		},
		accessories = {
			acc({
				name = "Crack1",
				part = "B11",
				size = { 7, 0.25, 0.1 },
				offset = { 0.5, 1.2, -1.06 },
				rot = { 0, 0, 20 },
				color = "#FF2A1A",
				material = "Neon",
				transparency = 1,
			}),
			acc({
				name = "Crack2",
				part = "B11",
				size = { 0.25, 9, 0.1 },
				offset = { -1.4, -0.5, -1.06 },
				rot = { 0, 0, -12 },
				color = "#FF2A1A",
				material = "Neon",
				transparency = 1,
			}),
			acc({
				name = "Crack3",
				part = "B11",
				size = { 6, 0.25, 0.1 },
				offset = { 1, -2.6, -1.06 },
				rot = { 0, 0, -25 },
				color = "#FF2A1A",
				material = "Neon",
				transparency = 1,
			}),
		},
	},
	BatMark = {
		kind = "custom",
		displayName = "Bat mark",
		colors = {},
		noTag = true,
		rootHeight = 0.03,
		parts = {
			part({
				name = "Mark",
				size = { 0.7, 0.05, 3.4 },
				color = "#3A2614",
				transparency = 0.15,
			}),
		},
	},
	Lever = {
		kind = "custom",
		displayName = "Lever",
		colors = {},
		noTag = true,
		rootHeight = 0,
		parts = {
			part({
				name = "LeverBase",
				size = { 1.2, 0.6, 1.2 },
				color = "#5A5A60",
				material = "Metal",
			}),
			part({
				name = "Handle",
				size = { 0.25, 2.2, 0.25 },
				color = "#9A9AA0",
				material = "Metal",
			}),
		},
		joints = {
			{
				name = "LeverJoint",
				part0 = "LeverBase",
				part1 = "Handle",
				c0 = { 0, 0.3, 0 },
				c1 = { 0, -1.1, 0 },
			},
		},
	},
}

RigSpecs.characters = characters

return RigSpecs
