--!strict
-- Intro chants (voice_lines.md). Played the first time each character appears in gameplay
-- (VoiceService.playIntroChant), never inside cutscenes. chapter = 0: not tied to a chapter.
return {
	{
		id = "CHANT_TUNGTUNG",
		speaker = "TungTung",
		text = "Tung. Tung. Tung. Tung. Tung. Tung. Tung. Tung. Tung. Sahur!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_LIRILI",
		speaker = "Lirili",
		text = "Lirili, larila… tic, tac, tic, tac… il tempo si ferma.",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_BALLERINA",
		speaker = "Ballerina",
		text = "Ballerina Cappuccina, mi-mi-mi! Dance with me before the night!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_TRALALERO",
		speaker = "Tralalero",
		text = "Tralalero tralala! Did you hear? Did you HEAR? Nobody sleeps tonight!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_CHIMPANZINI",
		speaker = "Chimpanzini",
		text = "Chimpanzini Bananini, wa-wa-wa! Buy something, or go away!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_PATAPIM",
		speaker = "Patapim",
		text = "Brr brr… patapim. The forest remembers. The forest… patapim.",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_BOMBARDIRO",
		speaker = "Bombardiro",
		text = "Bombardiro Crocodilo! I fly, I see EVERYTHING from above!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_CAPPUCCINO",
		speaker = "Cappuccino",
		text = "Cappuccino… Assassino. Shhh. I was never here.",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_TRIPPITROPPI",
		speaker = "TrippiTroppi",
		text = "Trippi Troppi, troppa trippa! I swim in soup, I know all the gossip!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_BONECAAMBALABU",
		speaker = "BonecaAmbalabu",
		text = "Boneca Ambalabu… ambalabu… the frog with the wheels sees the night roads.",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_UDINDINDINDUN",
		speaker = "UdinDinDinDun",
		text = "Udin din din din dun! Udin din din din dun! I sing so the dark goes away!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_LAVACASATURNO",
		speaker = "LaVacaSaturno",
		text = "La Vaca Saturno Saturnita… moooo… from the stars I watch the little sun.",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_FRIGOCAMELO",
		speaker = "FrigoCamelo",
		text = "Frigo Camelo! Cold drinks, cold desert, cold… cold nights, eh?",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
	{
		id = "CHANT_GLORBOFRUTTODRILLO",
		speaker = "GlorboFruttodrillo",
		text = "Glorbo Fruttodrillo! Half fruit, half croc, one hundred percent drama!",
		chapter = 0,
		scene = "CHANT",
		hum = "none",
	},
}
