--!strict
-- Chapter 5 lines (screenplay.md 5-1 .. 5-5, cutscenes CS-15 .. CS-19).
return {
	{
		id = "C5_NARR_CODE",
		speaker = "Narrator",
		text = "Six. Seven. The numbers everyone shouts… are the numbers that open the way.",
		chapter = 5,
		scene = "5-1",
	},
	{
		id = "C5_NARR_WRONG",
		speaker = "Narrator",
		text = "The lock clicks. Wrong numbers. Somewhere far away, somebody shouts them every day.",
		chapter = 5,
		scene = "5-1",
	},
	{
		id = "C5_CAPPUCCINO_TUNNEL",
		speaker = "Cappuccino",
		text = "The carts. Get in. Lean when the rails split, duck when the beams come low.",
		chapter = 5,
		scene = "5-2",
	},
	{
		id = "C5_NARR_RIDE",
		speaker = "Narrator",
		text = "Behind you, the dark is moving. Lean left, lean right. Duck. Don't stop.",
		chapter = 5,
		scene = "5-2",
	},
	{
		id = "CS16_LIRILI_FOUND",
		speaker = "Lirili",
		text = "You… found me. Tic… tac…",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_FORTY",
		speaker = "Lirili",
		text = "Forty days ago, a little light fell into my mine. It was so scared.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_TOMORROW",
		speaker = "Lirili",
		text = "It kept asking one thing. Will you come back tomorrow?",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_FAMILY",
		speaker = "Lirili",
		text = "I taught it words. Clocks. Music. Ballerina taught it to dance. It was family.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_GAME",
		speaker = "Lirili",
		text = "It came from a game where everyone left. The last player pressed No. And it was alone. For years.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_EVERYWORD",
		speaker = "Lirili",
		text = "I taught it every word… except one. It never learned no. It only learned to make no disappear.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_GIALLINO_MAMMA",
		speaker = "Giallino",
		text = "Mamma Lirili? Are you leaving too?",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_STOPPING",
		speaker = "Lirili",
		text = "I'm not leaving you. I'm just… stopping.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_GEARS",
		speaker = "Lirili",
		text = "Three gears. Bring time back. And please… don't let it ride with you through the tunnel.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "CS16_LIRILI_AFRAID",
		speaker = "Lirili",
		text = "It's not evil. It's afraid. Just like you.",
		chapter = 5,
		scene = "CS-16",
	},
	{
		id = "C5_NARR_LEVERS",
		speaker = "Narrator",
		text = "Lirili's diary, the last page: Levers. Three, one, four, two. Never the other way.",
		chapter = 5,
		scene = "5-4",
	},
	{
		id = "C5_NARR_LEVERS_WRONG",
		speaker = "Narrator",
		text = "Wrong lever! The stone shifts…",
		chapter = 5,
		scene = "5-4",
	},
	{
		id = "C5_CAPPUCCINO_LEDGE",
		speaker = "Cappuccino",
		text = "Not the platforms. The wall. There is a ledge along the north wall. My sister found it once.",
		chapter = 5,
		scene = "5-4",
	},
	{
		id = "C5_NARR_MAZE",
		speaker = "Narrator",
		text = "Total darkness. Only your lantern. Something walks here too. Listen for your heart.",
		chapter = 5,
		scene = "5-4",
	},
	{
		id = "C5_NARR_GEAR",
		speaker = "Narrator",
		text = "A Truth Gear. It is warm, and it ticks.",
		chapter = 5,
		scene = "5-4",
	},
	{
		id = "CS17_CRUDELINO_NOMORE",
		speaker = "Crudelino",
		text = "NO MORE HIDING. NO MORE NO.",
		chapter = 5,
		scene = "CS-17",
	},
	{
		id = "CS17_CRUDELINO_BREAK",
		speaker = "Crudelino",
		text = "I BREAK EVERY BLOCK UNTIL I FIND YOU.",
		chapter = 5,
		scene = "CS-17",
	},
	{
		id = "C5_CRUDELINO_SCREAM",
		speaker = "Crudelino",
		text = "FOUND YOU!",
		chapter = 5,
		scene = "5-5",
		hum = "none",
	},
	{
		id = "C5_CRUDELINO_TAUNT",
		speaker = "Crudelino",
		text = "RUN! RUN! I LIKE IT WHEN YOU RUN!",
		chapter = 5,
		scene = "5-5",
	},
	{
		id = "C5_BOMBARDIRO_MARK",
		speaker = "Bombardiro",
		text = "Bombardiro Crocodilo! Mark it, I bomb it! BOMBS AWAY!",
		chapter = 5,
		scene = "5-5",
	},
	{
		id = "C5_BOMBARDIRO_HIT",
		speaker = "Bombardiro",
		text = "HIT! Bombardiro never misses! Mark him again!",
		chapter = 5,
		scene = "5-5",
	},
	{
		id = "C5_NARR_STALACTITES",
		speaker = "Narrator",
		text = "No bombs are coming. Throw stones at the stalactites when it stands below them.",
		chapter = 5,
		scene = "5-5",
	},
	{
		id = "CS18_BOMBARDIRO_ONEMORE",
		speaker = "Bombardiro",
		text = "One more for Lirili! BOMBS AWAY!",
		chapter = 5,
		scene = "CS-18",
	},
	{
		id = "CS18_BOMBARDIRO_TUNNEL",
		speaker = "Bombardiro",
		text = "Bombardiro… sees all… Tell Lirili… the tunnel was the best thing we built.",
		chapter = 5,
		scene = "CS-18",
	},
	{
		id = "C5_NARR_CLIMB",
		speaker = "Narrator",
		text = "The cave is falling. Climb. Don't look down.",
		chapter = 5,
		scene = "5-5",
	},
}
