--!strict
-- Chapter 3 lines (screenplay.md 3-1 .. 3-5, cutscenes CS-07 .. CS-09). Falsino reads the statements of the truth-or-lie rounds aloud (F_R<round>_<n>).
return {
	{
		id = "C3_GIALLINO_JOURNAL",
		speaker = "Giallino",
		text = "A mystery! Giallino loves mysteries. It was Tung Tung, of course. But let's find clues anyway! For fun!",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_CAPPUCCINO_FOOTPRINTS",
		speaker = "Cappuccino",
		text = "Footprints. Too round for feet. Think about it.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_NARR_WELL",
		speaker = "Narrator",
		text = "Scratched into the wood: X 135. Z 20. Y minus 25. Under the hill… deep under.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_NARR_GLASS",
		speaker = "Narrator",
		text = "Melted glass. Not from fire. Something burned it from the inside… something yellow.",
		chapter = 3,
		scene = "3-2",
	},
	{
		id = "C3_NARR_DIARY",
		speaker = "Narrator",
		text = "Ballerina's diary: The little light asked me to dance forever again. I said not forever. It stopped smiling.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_LIRILI_NOTE",
		speaker = "Narrator",
		text = "If you hear this, I was wrong. The light I found cannot hear the word no.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_NARR_WRONG_CODE",
		speaker = "Narrator",
		text = "Click. Nothing. The box stays shut.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_BOMBARDIRO_SKY",
		speaker = "Bombardiro",
		text = "From the sky I saw a light. Orange. Floating. Going into Ballerina's house!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_BOMBARDIRO_POLITE",
		speaker = "Bombardiro",
		text = "Polite! Bombardiro likes polite. Here, a piece of my cave map. Do not lose it!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_BOMBARDIRO_RUDE",
		speaker = "Bombardiro",
		text = "Rude! No map for rude tourists! Come back with manners!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_BOMBARDIRO_SIXSEVEN",
		speaker = "Bombardiro",
		text = "SIX… SEVEN! Two clues at once! Bombardiro sees all!",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_PATAPIM_RIDDLE",
		speaker = "Patapim",
		text = "Who smiles in the dark but has no face? Answer me… patapim.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_PATAPIM_RIGHT",
		speaker = "Patapim",
		text = "Yes… the little light. Take this. It fell from it, in my roots… patapim.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_PATAPIM_WRONG",
		speaker = "Patapim",
		text = "No… no… think with your roots, not your eyes… patapim.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_FALSINO_FAKE",
		speaker = "Falsino",
		text = "That clue is fake! Someone put it there! Here, I found the REAL one for you.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_NARR_FAKE_BAT",
		speaker = "Narrator",
		text = "A bat with red paint on it. The paint is still wet. Too wet.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_NARR_FAKE_NOTE",
		speaker = "Narrator",
		text = "A note: TUNG WILL KILL EVERYONE. The letters are perfect squares. Like pixels.",
		chapter = 3,
		scene = "3-1",
	},
	{
		id = "C3_TRALALERO_WHERE",
		speaker = "Tralalero",
		text = "Under my bed, bro! Like a sigma. Tralalero does NOT go out at night!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_TRALALERO_SAW",
		speaker = "Tralalero",
		text = "A light! Yellow! Floating! Giallino said it was a firefly. A square firefly, fr fr.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_TRALALERO_WHO",
		speaker = "Tralalero",
		text = "Tung Tung! Everybody says Tung Tung. Wait… does everybody say it, or does Giallino say it?",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CHIMP_SAW",
		speaker = "Chimpanzini",
		text = "Nothing! I was counting bananas. Okay, okay… I saw yellow light by Ballerina's window. Happy?",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CHIMP_GLOW",
		speaker = "Chimpanzini",
		text = "My lanterns burn orange. Real fire. Yellow is NOT mine, wa-wa!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CHIMP_FANUM",
		speaker = "Chimpanzini",
		text = "Fanum tax! I take one item. Bananini rules, wa-wa-wa!",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CAPPUCCINO_WHO",
		speaker = "Cappuccino",
		text = "Someone who lost something. That's all you need to know.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CAPPUCCINO_LIGHT",
		speaker = "Cappuccino",
		text = "It smiles when nobody laughs. It counts us. Every night.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_CAPPUCCINO_SHOE",
		speaker = "Cappuccino",
		text = "…Because she would want someone to keep it.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_TUNG_HILL_1",
		speaker = "TungTung",
		text = "Tung… You came up the hill. Nobody comes up the hill.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_TUNG_HILL_2",
		speaker = "TungTung",
		text = "I knock so you wake up. Sleepers cannot say no. Sleepers just… go.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "C3_TUNG_HILL_3",
		speaker = "TungTung",
		text = "Say their names with me. Lirili. Frigo. Udin. Ballerina. Again tomorrow.",
		chapter = 3,
		scene = "3-3",
	},
	{
		id = "CS07_FALSINO",
		speaker = "Falsino",
		text = "Let's play a game! I say three things. One is a lie. Find it… or lose a little bit of you.",
		chapter = 3,
		scene = "CS-07",
	},
	{
		id = "C3_FALSINO_SPOTTED",
		speaker = "Falsino",
		text = "…A green eye? Oh. You noticed. Clever, clever little friends.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "C3_FALSINO_RIGHT",
		speaker = "Falsino",
		text = "Hmph. Lucky guess.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "C3_FALSINO_WRONG",
		speaker = "Falsino",
		text = "Wrong! A little bit of you is mine now.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "C3_FALSINO_AGAIN",
		speaker = "Falsino",
		text = "Too many wrong! Let's play AGAIN. And again. And again.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "CS08_FALSINO",
		speaker = "Falsino",
		text = "You're good at finding lies. Let's see if you like the truth.",
		chapter = 3,
		scene = "CS-08",
	},
	{
		id = "C3_NARR_ACCUSE",
		speaker = "Narrator",
		text = "Who knocks at night? Choose carefully. Someone will be locked away.",
		chapter = 3,
		scene = "3-5",
	},
	{
		id = "CS09_TUNG_KNOCK",
		speaker = "TungTung",
		text = "I knock so you wake up. That's all I ever did.",
		chapter = 3,
		scene = "CS-09T",
	},
	{
		id = "CS09_TUNG_NAMES",
		speaker = "TungTung",
		text = "Say their names. Every night. Promise me.",
		chapter = 3,
		scene = "CS-09T",
	},
	{
		id = "CS09_GIALLINO_GOOD",
		speaker = "Giallino",
		text = "Good job, detectives! See? Saying yes is easy.",
		chapter = 3,
		scene = "CS-09",
	},
	{
		id = "CS09_GIALLINO_GOODSHORT",
		speaker = "Giallino",
		text = "Good job!",
		chapter = 3,
		scene = "CS-09C",
	},
	{
		id = "CS09_CAPPUCCINO_SISTER",
		speaker = "Cappuccino",
		text = "I was only looking for my sister.",
		chapter = 3,
		scene = "CS-09C",
	},
	{
		id = "CS09_BOMBARDIRO_SHOUT",
		speaker = "Bombardiro",
		text = "You lock up BOMBARDIRO?! Bombardiro who watches the sky for you?!",
		chapter = 3,
		scene = "CS-09B",
	},
	{
		id = "CS09_BOMBARDIRO_SAD",
		speaker = "Bombardiro",
		text = "Lirili trusted me. Now nobody does.",
		chapter = 3,
		scene = "CS-09B",
	},
	{
		id = "CS09_GIALLINO_NOTSURE",
		speaker = "Giallino",
		text = "…Not sure? That's not a yes.",
		chapter = 3,
		scene = "CS-09N",
	},
	{
		id = "F_R1_1",
		speaker = "Falsino",
		text = "Tung Tung knocks to hurt you.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R1_2",
		speaker = "Falsino",
		text = "Lirili built the clock tower.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R1_3",
		speaker = "Falsino",
		text = "Ballerina left by herself.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R2_1",
		speaker = "Falsino",
		text = "Lirili found a little light in the mine.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R2_2",
		speaker = "Falsino",
		text = "The bell rang by itself.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R2_3",
		speaker = "Falsino",
		text = "Giallino was home all night.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R3_1",
		speaker = "Falsino",
		text = "Ballerina's door broke from the outside.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R3_2",
		speaker = "Falsino",
		text = "Cappuccino is Ballerina's brother.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R3_3",
		speaker = "Falsino",
		text = "The footprints were too round for feet.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R4_1",
		speaker = "Falsino",
		text = "Patapim speaks in riddles.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R4_2",
		speaker = "Falsino",
		text = "Six and seven are just numbers.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R4_3",
		speaker = "Falsino",
		text = "Giallino never lies.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R5_1",
		speaker = "Falsino",
		text = "Bombardiro saw a floating light.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R5_2",
		speaker = "Falsino",
		text = "Tung Tung says names every night.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R5_3",
		speaker = "Falsino",
		text = "Lirili left the valley on a train.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R6_1",
		speaker = "Falsino",
		text = "Frigo and Udin vanished at night.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R6_2",
		speaker = "Falsino",
		text = "Lanterns keep the dark away.",
		chapter = 3,
		scene = "3-4",
	},
	{
		id = "F_R6_3",
		speaker = "Falsino",
		text = "Nobody ever said no to Giallino.",
		chapter = 3,
		scene = "3-4",
	},
}
