--!strict
-- Chapter 2 lines. CS-05 text is from cutscenes.md (it wins inside cutscenes).
return {
	-- CS-05 "Ballerina's last dance"
	{
		id = "CS05_GIALLINO_FOREVER",
		speaker = "Giallino",
		text = "You dance so beautifully. Dance with me forever?",
		chapter = 2,
		scene = "CS-05",
	},
	{
		id = "CS05_BALLERINA_TIRED",
		speaker = "Ballerina",
		text = "I'm tired, little light. I'll dance again tomorrow.",
		chapter = 2,
		scene = "CS-05",
	},
	{
		id = "CS05_GIALLINO_TOMORROW",
		speaker = "Giallino",
		text = "Tomorrow? Everyone says tomorrow. Then they leave.",
		chapter = 2,
		scene = "CS-05",
	},
	{
		id = "CS05_BALLERINA_NOT_FOREVER",
		speaker = "Ballerina",
		text = "No, sweetheart. Not forever. Nobody can do anything forever.",
		chapter = 2,
		scene = "CS-05",
		hum = "no",
	},
	{
		id = "CS05_GIALLINO_WELCOME",
		speaker = "Giallino",
		text = "Now you'll never leave. You're welcome.",
		chapter = 2,
		scene = "CS-05",
	},
	{
		id = "CS04_NARR",
		speaker = "Narrator",
		text = "And then… the knocking began.",
		chapter = 2,
		scene = "CS-04",
	},
	{
		id = "CS04_TUNG_KNOCK",
		speaker = "TungTung",
		text = "Tung… tung… tung…",
		chapter = 2,
		scene = "CS-04",
		hum = "none",
	},
	{
		id = "CS04_GIALLINO_DONT",
		speaker = "Giallino",
		text = "Don't open it. Don't open it. Don't. Open. It.",
		chapter = 2,
		scene = "CS-04",
	},
	{
		id = "CS04A_GIALLINO_WHY",
		speaker = "Giallino",
		text = "I said don't. You didn't say yes. Why?",
		chapter = 2,
		scene = "CS-04A",
	},
	{
		id = "C2_GIALLINO_HIDE",
		speaker = "Giallino",
		text = "Hide, hide! Hold your breath. Giallino will count. One… two…",
		chapter = 2,
		scene = "2-2",
	},
	{
		id = "C2_GIALLINO_BARRICADE",
		speaker = "Giallino",
		text = "Boxes! Push the boxes to the door! Quick quick quick!",
		chapter = 2,
		scene = "2-2",
	},
	{
		id = "C2_GIALLINO_FIRE",
		speaker = "Giallino",
		text = "Keep the fire warm, friends. The dark doesn't like fire. Wood goes in the fire!",
		chapter = 2,
		scene = "2-3",
	},
	{
		id = "C2_GIALLINO_FIRE_LOW",
		speaker = "Giallino",
		text = "The fire is getting small… like you.",
		chapter = 2,
		scene = "2-3",
	},
	{
		id = "C2_GIALLINO_DAWN",
		speaker = "Giallino",
		text = "Shhh. Look out the window. Something beautiful.",
		chapter = 2,
		scene = "2-3",
	},
	{
		id = "CS06_TRALALERO_SCREAM",
		speaker = "Tralalero",
		text = "AAAAAH! Tralalaaa!",
		chapter = 2,
		scene = "CS-06",
		hum = "none",
	},
	{
		id = "CS06_TRALALERO_GONE",
		speaker = "Tralalero",
		text = "Ballerina is GONE! Her door is broken… from the inside! Tralala, what does it mean?!",
		chapter = 2,
		scene = "CS-06",
	},
	{
		id = "CS06_GIALLINO_TUNG",
		speaker = "Giallino",
		text = "It was Tung Tung Tung Sahur. I saw everything. And Giallino never lies.",
		chapter = 2,
		scene = "CS-06",
	},
	{
		id = "CS06_CAPPUCCINO",
		speaker = "Cappuccino",
		text = "A light that says it never lies… Think about it. And don't tell it I talked to you.",
		chapter = 2,
		scene = "CS-06",
	},
}
