--!strict
-- Chapter 1 lines. CS-02 text is from cutscenes.md (it wins inside cutscenes).
return {
	-- CS-02 "Hi, I'm Giallino"
	{
		id = "CS02_GIALLINO_HELLO",
		speaker = "Giallino",
		text = "Ciao, new friends! I'm Giallino, your little light!",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS02_GIALLINO_TRUTH",
		speaker = "Giallino",
		text = "I always tell the truth. Giallino never lies!",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS02_GIALLINO_RULE",
		speaker = "Giallino",
		text = "Rule number one: when Giallino asks, you say yes. Easy, right?",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS02_GIALLINO_PROMISE",
		speaker = "Giallino",
		text = "Do you promise to always listen to me?",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS02_GIALLINO_YES",
		speaker = "Giallino",
		text = "Yay! Best friends forever. FOREVER.",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS02_GIALLINO_NO",
		speaker = "Giallino",
		text = "…Haha! Funny. You'll say yes later.",
		chapter = 1,
		scene = "CS-02",
	},
	{
		id = "CS01_NARR_1",
		speaker = "Narrator",
		text = "Brainrot Valley. A quiet village.",
		chapter = 1,
		scene = "CS-01",
	},
	{
		id = "CS01_NARR_2",
		speaker = "Narrator",
		text = "Nobody leaves after dark…",
		chapter = 1,
		scene = "CS-01",
	},
	{
		id = "CS01_NARR_3",
		speaker = "Narrator",
		text = "…and nobody remembers why.",
		chapter = 1,
		scene = "CS-01",
	},
	{
		id = "C1_GIALLINO_SAFE",
		speaker = "Giallino",
		text = "I'll keep you safe. Just do what I say, okay?",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_GIALLINO_TASKS",
		speaker = "Giallino",
		text = "Wood is to the north. Seventeen blocks. I counted them for you!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_GIALLINO_LANTERN",
		speaker = "Giallino",
		text = "Get a lantern from Chimpanzini. And bread! Friends need bread.",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_CHIMP_LANTERN",
		speaker = "Chimpanzini",
		text = "Chimpanzini Bananini, wa-wa-wa! You want lantern? Lantern is good. Night is NOT good.",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_CHIMP_TAKE",
		speaker = "Chimpanzini",
		text = "Take, take. First lantern free for new friends. Second one, you pay double, wa-wa!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_TRALALERO_NIGHT",
		speaker = "Tralalero",
		text = "Tralalero tralala! No cap, nobody sleeps tonight, it's giving scary, fr fr!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_TRALALERO_DAY",
		speaker = "Tralalero",
		text = "No cap, Tung Tung has zero rizz at night, it's giving villain arc, sigma skibidi suspicious, tralala!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_STRAWBERRY",
		speaker = "Strawberry",
		text = "You ate MY banana bread?!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_BANANA",
		speaker = "Banana",
		text = "It was OUR bread! This is Love Island, not Lonely Island!",
		chapter = 1,
		scene = "1-3",
	},
	{
		id = "C1_GIALLINO_APPLE",
		speaker = "Giallino",
		text = "See the red apple up there? Jump on the leaves! Don't fall in the river, it's wet. Very wet.",
		chapter = 1,
		scene = "1-4",
	},
	{
		id = "C1_GIALLINO_APPLE_DONE",
		speaker = "Giallino",
		text = "Yay! You're so good at jumping. Giallino is proud. So proud.",
		chapter = 1,
		scene = "1-4",
	},
	{
		id = "CS03_TRALALERO",
		speaker = "Tralalero",
		text = "Lirili is gone three days… who rings the bell, eh?!",
		chapter = 1,
		scene = "CS-03",
	},
	{
		id = "CS03_GIALLINO_INSIDE",
		speaker = "Giallino",
		text = "Inside, inside! The night is not for you. Go to the inn. Now, please. :)",
		chapter = 1,
		scene = "CS-03",
	},
	{
		id = "C1_GIALLINO_HURRY",
		speaker = "Giallino",
		text = "Hurry, hurry! The fog is hungry tonight.",
		chapter = 1,
		scene = "1-6",
	},
	{
		id = "C1_GIALLINO_LATE",
		speaker = "Giallino",
		text = "Too slow! Giallino said NOW. Run inside!",
		chapter = 1,
		scene = "1-6",
	},
}
