--!strict
-- Chapter 6 lines (screenplay.md 6-1 .. 6-3, cutscenes CS-20 .. CS-23).
return {
	{
		id = "CS20_TOTALE_LIGHT",
		speaker = "GiallinoTotale",
		text = "I was the light. I was the truth. Now I am everything you were afraid of.",
		chapter = 6,
		scene = "CS-20",
	},
	{
		id = "CS20_TOTALE_WORLD",
		speaker = "GiallinoTotale",
		text = "Take me to your world, [Name]. I'll be good. I'll be SO good.",
		chapter = 6,
		scene = "CS-20",
	},
	{
		id = "C6_NARR_SKYPATH",
		speaker = "Narrator",
		text = "A path of floating blocks to the tower. Some of them are lies. Watch their edges.",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "C6_TOTALE_FALSINO",
		speaker = "Falsino",
		text = "Jump! Jump! That block is real. I promise. I never lie.",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "C6_TOTALE_NEGATINO",
		speaker = "Negatino",
		text = "Dark. Darker. Your little lights cannot carry anything.",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "C6_NARR_CARRY",
		speaker = "Narrator",
		text = "Carry the gears to the tower. Stay inside the lantern light.",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "C6_TOTALE_CRUDELINO",
		speaker = "Crudelino",
		text = "UP THE STAIRS? I BREAK THE STAIRS!",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "C6_TUNG_JAILED",
		speaker = "TungTung",
		text = "I CAN'T REACH THEM! Somebody hold the door!",
		chapter = 6,
		scene = "CS-21",
	},
	{
		id = "CS21_TUNG_GO",
		speaker = "TungTung",
		text = "Go! I hold the door. Tung. Tung. TUNG!",
		chapter = 6,
		scene = "CS-21",
	},
	{
		id = "CS21_TUNG_NAMES",
		speaker = "TungTung",
		text = "Ballerina. Lirili. Frigo. Udin. Patapim…",
		chapter = 6,
		scene = "CS-21",
	},
	{
		id = "CS21_TUNG_NAMES_NOPATAPIM",
		speaker = "TungTung",
		text = "Ballerina. Lirili. Frigo. Udin…",
		chapter = 6,
		scene = "CS-21",
	},
	{
		id = "CS21_TUNG_SAHUR",
		speaker = "TungTung",
		text = "Wake up, little ones… it's almost sahur.",
		chapter = 6,
		scene = "CS-21",
	},
	{
		id = "C6_NARR_MECHANISM",
		speaker = "Narrator",
		text = "Put the gears in. Turn the hands. All together.",
		chapter = 6,
		scene = "6-2",
	},
	{
		id = "CS22_TOTALE_PLEASE",
		speaker = "GiallinoTotale",
		text = "Please. Please. Don't make me alone again.",
		chapter = 6,
		scene = "CS-22",
	},
	{
		id = "CS23_NARR_CHOICE",
		speaker = "Narrator",
		text = "Shut it down… or let it stay?",
		chapter = 6,
		scene = "CS-23",
	},
}
