--!strict
-- Chapter 4 lines (screenplay.md 4-1 .. 4-5, cutscenes CS-10 .. CS-14).
return {
	{
		id = "CS10_GIALLINO_WHY",
		speaker = "Giallino",
		text = "Why did you say no, [Name]? I s-saw you. [Hiding spot]. Twice.",
		chapter = 4,
		scene = "CS-10",
	},
	{
		id = "CS10_NEGATINO",
		speaker = "Negatino",
		text = "Your lantern is so small. The dark is so big. Why do you even try?",
		chapter = 4,
		scene = "CS-10",
	},
	{
		id = "C4_NEGATINO_TAUNT_1",
		speaker = "Negatino",
		text = "Give up. The dark is softer than you think.",
		chapter = 4,
		scene = "4-2",
	},
	{
		id = "C4_NEGATINO_TAUNT_2",
		speaker = "Negatino",
		text = "Every light goes out. Even yours.",
		chapter = 4,
		scene = "4-2",
	},
	{
		id = "C4_NEGATINO_TAUNT_3",
		speaker = "Negatino",
		text = "Shhh. Stop trying. Sleep.",
		chapter = 4,
		scene = "4-2",
	},
	{
		id = "C4_NARR_OIL",
		speaker = "Narrator",
		text = "Four braziers. Four bottles of oil somewhere in the alleys. Light them all.",
		chapter = 4,
		scene = "4-2",
	},
	{
		id = "C4_NEGATINO_PHASE2",
		speaker = "Negatino",
		text = "You lit my square? I will eat your fire. One. By. One.",
		chapter = 4,
		scene = "4-2",
	},
	{
		id = "CS12_TUNG_WAKE",
		speaker = "TungTung",
		text = "WAKE UP! It is not me! It was never me!",
		chapter = 4,
		scene = "CS-12",
	},
	{
		id = "CS12_TUNG_KNOCKED",
		speaker = "TungTung",
		text = "Every night I knocked so you would wake up with the light on. Sleepers can't say no. Sleepers just disappear.",
		chapter = 4,
		scene = "CS-12",
	},
	{
		id = "CS12_TUNG_NAMES",
		speaker = "TungTung",
		text = "Ballerina. Lirili. Frigo. Udin… I say their names so they don't fade.",
		chapter = 4,
		scene = "CS-12",
	},
	{
		id = "CS12_TUNG_RUN",
		speaker = "TungTung",
		text = "RUN to the forest! Before the light comes back WRONG!",
		chapter = 4,
		scene = "CS-12",
	},
	{
		id = "CS13_GIALLINO",
		speaker = "Giallino",
		text = "Where are you going? NOBODY LEAVES.",
		chapter = 4,
		scene = "CS-13",
	},
	{
		id = "C4_GIALLINO_CHASE_1",
		speaker = "Giallino",
		text = "Come back! Giallino is lonely!",
		chapter = 4,
		scene = "4-4",
	},
	{
		id = "C4_GIALLINO_CHASE_2",
		speaker = "Giallino",
		text = "Hide-and-seek? I always find you. ALWAYS.",
		chapter = 4,
		scene = "4-4",
	},
	{
		id = "C4_PATAPIM_FAR",
		speaker = "Patapim",
		text = "Brr… brr… go west, little ones… the long way round… patapim!",
		chapter = 4,
		scene = "4-5",
	},
	{
		id = "CS14_PATAPIM_BEHIND",
		speaker = "Patapim",
		text = "Brr… brr… The light is behind you. The roots are below you.",
		chapter = 4,
		scene = "CS-14",
	},
	{
		id = "CS14_PATAPIM_ROOTS",
		speaker = "Patapim",
		text = "Follow the roots, not the light. Light lies tonight.",
		chapter = 4,
		scene = "CS-14",
	},
	{
		id = "CS14_PATAPIM_REMEMBER",
		speaker = "Patapim",
		text = "I was the first to fall here. Somebody… remember my name.",
		chapter = 4,
		scene = "CS-14",
	},
}
