--!strict
-- Ending lines (CS-E1 Dawn, CS-E2 Endless Night, CS-E3 Sahur).
return {
	{
		id = "E1_GIALLINO_GOOD",
		speaker = "Giallino",
		text = "…Did I… do good?",
		chapter = 6,
		scene = "CS-E1",
	},
	{
		id = "E1_LIRILI_SORRY",
		speaker = "Lirili",
		text = "…I'm sorry, little light.",
		chapter = 6,
		scene = "CS-E1",
	},
	{
		id = "E1_TUNG_SAHUR",
		speaker = "TungTung",
		text = "…Is it sahur yet?",
		chapter = 6,
		scene = "CS-E1",
	},
	{
		id = "E1_NARR_SUN",
		speaker = "Narrator",
		text = "The sun rose. A real one. And for the first time, nobody knocked.",
		chapter = 6,
		scene = "CS-E1",
	},
	{
		id = "E2_GIALLINO_STAYED",
		speaker = "Giallino",
		text = "You stayed! Everyone stays now. Forever.",
		chapter = 6,
		scene = "CS-E2",
	},
	{
		id = "E2_GIALLINO_WELCOME",
		speaker = "Giallino",
		text = "Welcome back, friends! I'm Giallino, your little light…",
		chapter = 6,
		scene = "CS-E2",
	},
	{
		id = "E3_LIRILI_HELLO",
		speaker = "Lirili",
		text = "Hello, little light.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_GIALLINO_LEAVING",
		speaker = "Giallino",
		text = "Are you leaving? Everybody leaves when they say no.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_LIRILI_LISTEN",
		speaker = "Lirili",
		text = "Listen. No doesn't mean goodbye. I can say no… and still come back tomorrow.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_LIRILI_REPEAT",
		speaker = "Lirili",
		text = "Repeat after me. No.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_GIALLINO_NO",
		speaker = "Giallino",
		text = "…No.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_BALLERINA_TOMORROW",
		speaker = "Ballerina",
		text = "I told you. Not forever. Just… tomorrow.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_TUNG_NAMES",
		speaker = "TungTung",
		text = "Ballerina! Lirili! Bombardiro! Patapim!… Giallino.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_GIALLINO_NAME",
		speaker = "Giallino",
		text = "…That's my name.",
		chapter = 6,
		scene = "CS-E3",
	},
	{
		id = "E3_TUNG_MORNING",
		speaker = "TungTung",
		text = "Tung… tung… tung… Good morning, Brainrot Valley.",
		chapter = 6,
		scene = "CS-E3",
	},
}
