--!strict
-- Story place client entry point: audio, cutscenes, HUD and the gameplay clients.
local RunService = game:GetService("RunService")
local StarterGui = game:GetService("StarterGui")

local Shared = game:GetService("ReplicatedStorage"):WaitForChild("Shared")
local Audio = require(Shared:WaitForChild("Audio"))

local Root = script.Parent
local Settings = require(Root:WaitForChild("Settings"))
local AudioFolder = Root:WaitForChild("Audio")
local UI = Root:WaitForChild("UI")
local Gameplay = Root:WaitForChild("Gameplay")
local MusicDirector = require(AudioFolder:WaitForChild("MusicDirector"))
local AmbienceDirector = require(AudioFolder:WaitForChild("AmbienceDirector"))
local Footsteps = require(AudioFolder:WaitForChild("Footsteps"))
local VoiceService = require(AudioFolder:WaitForChild("VoiceService"))
local CutsceneEngine = require(Root:WaitForChild("Cutscene"):WaitForChild("CutsceneEngine"))
local VoteUI = require(UI:WaitForChild("VoteUI"))
local Hud = require(UI:WaitForChild("Hud"))
local DialogueUI = require(UI:WaitForChild("DialogueUI"))
local JournalUI = require(UI:WaitForChild("JournalUI"))
local QTEUI = require(UI:WaitForChild("QTEUI"))
local DeathUI = require(UI:WaitForChild("DeathUI"))
local DownedClient = require(Gameplay:WaitForChild("DownedClient"))
local WorldFx = require(Gameplay:WaitForChild("WorldFx"))
local FakeBlocks = require(Gameplay:WaitForChild("FakeBlocks"))
local GiallinoClient = require(Gameplay:WaitForChild("GiallinoClient"))
local MapClient = require(Gameplay:WaitForChild("MapClient"))
local MinecartClient = require(Gameplay:WaitForChild("MinecartClient"))

-- our own HUD shows HP; the Roblox health bar would show the hidden real value
pcall(function()
	StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Health, false)
end)

Audio.init()
local function applyVolumes()
	local s = Settings.get()
	Audio.setGroupVolume("Music", s.musicVolume)
	Audio.setGroupVolume("Ambience", s.ambienceVolume)
	Audio.setGroupVolume("SFX", s.sfxVolume)
	Audio.setGroupVolume("Voice", s.voiceVolume)
end
applyVolumes()
Settings.Changed:Connect(applyVolumes)

MusicDirector.init()
AmbienceDirector.init()
Footsteps.init()
VoiceService.init()
VoteUI.init()
CutsceneEngine.init()
Hud.setVoice(function(lineId: string)
	VoiceService.say(lineId)
end)
Hud.init()
DialogueUI.init()
JournalUI.init()
QTEUI.init()
DeathUI.init()
WorldFx.init()
FakeBlocks.init()
DownedClient.init()
GiallinoClient.init()
MapClient.init()
MinecartClient.init()

if RunService:IsStudio() then
	require(Root:WaitForChild("Dev"):WaitForChild("DebugClient")).init()
end
