--!strict
-- Block palette from map.md section 2: textures per face + fallback material and color.
-- `footstep` is the Block attribute Footsteps reads. Variants (roof colors, door colors) reuse a
-- base block with another color: Blocks.get(name) returns the def, MapBuilder may tint it.

export type BlockDef = {
	top: string?, -- TextureIds key for the top face
	side: string?, -- TextureIds key for the four side faces
	bottom: string?, -- TextureIds key for the bottom face
	material: string, -- Enum.Material name (fallback look and physics)
	color: string, -- hex
	transparency: number?,
	footstep: string, -- Footsteps Block attribute
	collide: boolean?, -- default true
	light: { color: string, range: number, brightness: number }?,
}

local Blocks: { [string]: BlockDef } = {
	grass = {
		top = "grass_top",
		side = "grass_side",
		bottom = "dirt",
		material = "Grass",
		color = "#4C8030",
		footstep = "grass",
	},
	dirt = {
		top = "dirt",
		side = "dirt",
		bottom = "dirt",
		material = "Ground",
		color = "#704D33",
		footstep = "dirt",
	},
	dirt_path = {
		top = "dirt_path",
		side = "dirt",
		bottom = "dirt",
		material = "Ground",
		color = "#8C7046",
		footstep = "dirt_path",
	},
	stone = {
		top = "stone",
		side = "stone",
		bottom = "stone",
		material = "Slate",
		color = "#707070",
		footstep = "stone",
	},
	cobblestone = {
		top = "cobblestone",
		side = "cobblestone",
		bottom = "cobblestone",
		material = "Cobblestone",
		color = "#767676",
		footstep = "cobblestone",
	},
	mossy_cobblestone = {
		top = "mossy_cobblestone",
		side = "mossy_cobblestone",
		bottom = "mossy_cobblestone",
		material = "Cobblestone",
		color = "#5E6E4E",
		footstep = "mossy_cobblestone",
	},
	oak_planks = {
		top = "oak_planks",
		side = "oak_planks",
		bottom = "oak_planks",
		material = "WoodPlanks",
		color = "#9C7646",
		footstep = "oak_planks",
	},
	oak_log = {
		top = "oak_log_top",
		side = "oak_log_side",
		bottom = "oak_log_top",
		material = "Wood",
		color = "#604428",
		footstep = "oak_log",
	},
	pale_log = {
		top = "oak_log_top",
		side = "pale_log_side",
		bottom = "oak_log_top",
		material = "Wood",
		color = "#DCDCD2",
		footstep = "pale_log",
	},
	leaves = {
		top = "leaves",
		side = "leaves",
		bottom = "leaves",
		material = "Grass",
		color = "#2E6222",
		transparency = 0.05,
		footstep = "leaves",
	},
	sand = {
		top = "sand",
		side = "sand",
		bottom = "sand",
		material = "Sand",
		color = "#D8C896",
		footstep = "sand",
	},
	gravel = {
		top = "gravel",
		side = "gravel",
		bottom = "gravel",
		material = "Pebble",
		color = "#6E6864",
		footstep = "gravel",
	},
	water = {
		top = "water",
		side = "water",
		bottom = "water",
		material = "Glass",
		color = "#3052A0",
		transparency = 0.35,
		footstep = "sand",
		collide = false,
	},
	lava = {
		top = "lava",
		side = "lava",
		bottom = "lava",
		material = "Neon",
		color = "#E07018",
		footstep = "stone",
		light = { color = "#FF8A2A", range = 16, brightness = 1.2 },
	},
	bricks = {
		top = "bricks",
		side = "bricks",
		bottom = "bricks",
		material = "Brick",
		color = "#9A4636",
		footstep = "bricks",
	},
	glass = {
		top = "glass",
		side = "glass",
		bottom = "glass",
		material = "Glass",
		color = "#CFE8F0",
		transparency = 0.7,
		footstep = "stone",
	},
	coal_ore = {
		top = "coal_ore",
		side = "coal_ore",
		bottom = "coal_ore",
		material = "Slate",
		color = "#5A5A5A",
		footstep = "coal_ore",
	},
	iron_ore = {
		top = "iron_ore",
		side = "iron_ore",
		bottom = "iron_ore",
		material = "Slate",
		color = "#8A7A6A",
		footstep = "iron_ore",
	},
	gold_ore = {
		top = "gold_ore",
		side = "gold_ore",
		bottom = "gold_ore",
		material = "Slate",
		color = "#9A8A4A",
		footstep = "gold_ore",
	},
	glowstone_ore = {
		top = "glowstone_ore",
		side = "glowstone_ore",
		bottom = "glowstone_ore",
		material = "Slate",
		color = "#B0A050",
		footstep = "glowstone_ore",
		light = { color = "#FFE08A", range = 6, brightness = 0.8 },
	},
	hay = {
		top = "hay_side",
		side = "hay_side",
		bottom = "hay_side",
		material = "Fabric",
		color = "#C8AA32",
		footstep = "hay",
	},
	wool_red = {
		top = "wool_red",
		side = "wool_red",
		bottom = "wool_red",
		material = "Fabric",
		color = "#A42E2E",
		footstep = "grass",
	},
	-- untextured helpers (decor and props)
	wheat = { material = "Grass", color = "#D8B848", footstep = "grass", collide = false },
	flower_red = {
		material = "SmoothPlastic",
		color = "#D83838",
		footstep = "grass",
		collide = false,
	},
	flower_yellow = {
		material = "SmoothPlastic",
		color = "#F0D040",
		footstep = "grass",
		collide = false,
	},
	tall_grass = { material = "Grass", color = "#5C9A3A", footstep = "grass", collide = false },
	cloud = {
		material = "SmoothPlastic",
		color = "#FFFFFF",
		transparency = 0.1,
		footstep = "stone",
		collide = false,
	},
	iron = { material = "Metal", color = "#B8B8C0", footstep = "stone" },
	rail = { material = "Metal", color = "#8A8A90", footstep = "gravel" },
	torch = { material = "Neon", color = "#FFB040", footstep = "stone", collide = false },
	black = { material = "SmoothPlastic", color = "#141414", footstep = "stone" },
	white = { material = "SmoothPlastic", color = "#F0F0E8", footstep = "stone" },
	pink = { material = "Fabric", color = "#F2A7C3", footstep = "grass" },
	cobweb = {
		material = "SmoothPlastic",
		color = "#F0F0F0",
		transparency = 0.5,
		footstep = "stone",
		collide = false,
	},
	mushroom = {
		material = "SmoothPlastic",
		color = "#C83A2A",
		footstep = "grass",
		collide = false,
	},
	fern = { material = "Grass", color = "#3E7A2E", footstep = "grass", collide = false },
	reed = { material = "Grass", color = "#7A9A4A", footstep = "grass", collide = false },
}

return Blocks
